name: workflow01
on: [push, deployment]
jobs: 
  test:
    runs-on: windows-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install Nodejs
        uses: actions/setup-node@v3
        with: 
          node-version: 16
      - name: Install dependencies
        uses: npm ci
      - name: Run tests
        uses: npm test
  lint:
    runs-on: windows-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install Nodejs
        uses: actions/setup-node@v3
        with: 
          node-version: 16 
      - name: Install dependencies
        uses: npm ci
      - name: lint check
        uses: npm lint
  build:
    runs-on: windows-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install Nodejs
        uses: actions/setup-node@v3
        with: 
          node-version: 16
      - name: Install dependencies
        uses: npm ci
      - name: Build project
        run: npm run build
      - name: deploy
        echo: "Deploying to s3 ..."